name: Sync to Gitee

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  sync:
    name: Sync GitHub to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: https://github.com/fool-cat/fc_embed.git
          destination-repo: git@gitee.com:lord-it-over-a-district/fc_embed.git
